name: github pages

on:
  push:
    branches:
      # ğŸ”½ ç™ºç«ã‚¿ã‚¤ãƒŸãƒ³ã‚°ã‚’å„ã‚¯ãƒ©ã‚¹ã®mainãƒ–ãƒ©ãƒ³ãƒã‚’æŒ‡å®š
      - class01-main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: "0.4.8"
          # mdbook-version: 'latest'

      # mdãƒ•ã‚¡ã‚¤ãƒ«ã®ãƒ“ãƒ«ãƒ‰
      - run: mdbook build

      # ã‚µãƒ³ãƒ—ãƒ«ãƒ•ã‚¡ã‚¤ãƒ«ã‚’zipåœ§ç¸®ã—ã¦ãƒ“ãƒ«ãƒ‰ã—ãŸãƒ•ã‚¡ã‚¤ãƒ«ç¾¤ã«è¿½åŠ 
      - run: |
          mkdir ./book/samples
          cd samples
          find . \! -name '*.zip' -type d -exec zip -r {}.zip {} \;
          mv *.zip ../book/samples

      # ãƒ“ãƒ«ãƒ‰ã•ã‚ŒãŸãƒ•ã‚¡ã‚¤ãƒ«ç¾¤ã‚’gh-pagesãƒ–ãƒ©ãƒ³ãƒã«ãƒ‡ãƒ—ãƒ­ã‚¤
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        # ğŸ”½ ã‚½ãƒ¼ã‚¹ã‚’å„ã‚¯ãƒ©ã‚¹ã®mainãƒ–ãƒ©ãƒ³ãƒã‚’æŒ‡å®š
        if: github.ref == 'refs/heads/class01-main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir:
            ./book
            # ğŸ”½ ãƒ‡ãƒ—ãƒ­ã‚¤å…ˆã‚’å„ã‚¯ãƒ©ã‚¹ã®deployãƒ–ãƒ©ãƒ³ãƒã‚’æŒ‡å®š
          publish_branch: class01-deploy
